services:
    eav.document_processor:
        arguments: ['@validator']
        class: EavBundle\Service\EavDocumentProcessor

    eav.value_typecast:
        class: EavBundle\Service\EavValueTypeCast

    eav.eav_document_subscriber:
        class: EavBundle\EventSubscriber\EavDocumentSubscriber
        arguments: ['@eav.document_processor', '@eav.value_typecast']
        tags:
            - { name: doctrine.event_subscriber }

    eav.service.grid:
        class: EavBundle\Service\EavGrid
        calls:
            - [setTranslator, ['@translator.default']]
            - [setDirector, ['@grid.director']]
            - [setGridBuilder, ['@grid.builder.jsgrid']]
            - [setColumnFactory, ['@grid.column_factory']]

    eav.query_filter_factory:
        class: EavBundle\Service\Query\Filter\Factory

    eav.query_filter_service:
        class: EavBundle\Service\Query\Filter\Service
        arguments: ['@eav.query_filter_factory']
        calls:
            - [setEntityManager, ['@doctrine.orm.default_entity_manager']]

    eav.constraints_unique_document_validator:
        class: EavBundle\Validator\Constraints\EavUniqueDocumentConstraintValidator
        arguments: ['@doctrine.orm.default_entity_manager']
        tags:
            - { name: validator.constraint_validator }

    eav.constraints_value_collection_validator:
        class: EavBundle\Validator\Constraints\EavValueCollectionConstraintValidator
        arguments: ['@doctrine.orm.default_entity_manager', '@eav.document_processor']
        tags:
            - { name: validator.constraint_validator }

    eav.service.form_fields_builder:
        class: EavBundle\Service\EavFormFieldsBuilder
        arguments: ['@doctrine.orm.entity_manager']
